---  # tasks/check_system.yml

# Check if we're running Rocky Linux 9.x

- name: Make sure we're running Rocky Linux 9.x
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Rocky"
      - ansible_distribution_major_version is version('9', '=')
    fail_msg: "Please run this playbook on Rocky Linux 9.x only."

...
